sudo: false

services:
  - docker

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

before_script:
  - docker build -t maestro .

script:
  - docker run maestro bash -c "./vendor/bin/phpunit"
  - docker run maestro bash -c "./vendor/bin/phpunit --coverage-text"
  - docker run maestro bash -c "bash <(curl -s https://codecov.io/env)"
  - docker run maestro -i -t bash
  - docker exec -d maestro bash "./vendor/bin/phpunit --coverage-clover coverage.xml"
  - docker exec -d maestro bash "bash <(curl -s https://codecov.io/bash)"
